### PR TITLE
Fix NPE in PipeApplicationView. Use slash as path separator for loading

### PR DESCRIPTION
**Pull request by wlami**
Fixes the NPE at startup under JAVA 8 on my windows machine.

### CODE REVIEW

**Comment by sjdayday** [comment]
Thanks for suggesting this fix.  Others have reported similar problems, but
I think we'll need to look for something different than hard-coding the
path separator.  I hope to have time to research this soon.

best,
Steve

On Thu, Dec 3, 2015 at 1:08 PM, Wladislaw Mitzel <notifications@github.com>
wrote:

> Fixes the NPE at startup under JAVA 8 on my windows machine.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/sarahtattersall/PIPE/pull/98
> Commit Summary
>
>    - Fix NPE in PipeApplicationView. Use slash as path separator for
>    loading
>
> File Changes
>
>    - *M* pipe-gui/src/main/java/pipe/gui/PIPEConstants.java
>    <https://github.com/sarahtattersall/PIPE/pull/98/files#diff-0> (50)
>
> Patch Links:
>
>    - https://github.com/sarahtattersall/PIPE/pull/98.patch
>    - https://github.com/sarahtattersall/PIPE/pull/98.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sarahtattersall/PIPE/pull/98>.
>



-- 
Steve Doubleday
UC Irvine
Mathematical Behavioral Sciences
stevedoubleday@gmail.com
818-648-8381

**Comment by wlami** [comment]
Hi Steve,
in this case the "path" is used in order to load a resource from the classpath. The paths to classpath resources are handled like URLs which do always use forward slash `"/"`  as separator. So `File.separator` should not be used.
Regards,
Wlami

**Comment by sjdayday** [comment]
Hi Wlami,

Yes, I agree.  I've verified that all the current access is through
classpath resource loading, not through the file system.  I'll make the
fix.  Thanks.

Steve

On Sat, Jan 30, 2016 at 1:03 PM, Wladislaw Mitzel <notifications@github.com>
wrote:

> Hi Steve,
> in this case the "path" is used in order to load a resource from the
> classpath. The paths to classpath resources are handled like URLs which do
> always use forward slash "/" as separator. So File.separator should not
> be used.
> Regards,
> Wlami
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sarahtattersall/PIPE/pull/98#issuecomment-177300914>.
>



-- 
Steve Doubleday
UC Irvine
Mathematical Behavioral Sciences
stevedoubleday@gmail.com
818-648-8381

**Comment by sjdayday** [comment]
I modified the file-handling to always load resources, so this suggested approach will work for both example files and images.  It's incorporated into PIPE 5.0.2.   Thanks!

**Pull request closed without merging**
